

# ===========================
# Authentication 
# ===========================

### Auth Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username":  "admin",
    "password": "admin123"
}

#### Signup
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
  "username": "admin",
  "email": "admin@hotmail.com",
  "password": "admin123"
}


### Change password
PUT http://localhost:3000/api/auth/change-password/16
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxNiwiaWF0IjoxNzc3OTczNjI2LCJleHAiOjE3NzgwNjAwMjZ9.Hn4sBul8GCEScLJQomEuFsGJxGdfYYiWDIJ9663V8u4
Content-Type: application/json

{
  "old_password": "123456",
  "new_password": "123456"
}

# ===========================
# Dashboards
# =========================== 
### GET 
GET http://localhost:3000/api/getdashboards


### POST
POST http://localhost:3000/api/postdashboards
Content-Type: application/json

{
  "farm_id": "1",
  "farm_name": "test",
  "temperatures": "-10",
  "humidity":"-10",
  "ph": "-10"
}




# ===========================
# Farms
# ===========================
### GET 
GET http://localhost:3000/api/getfarm

### POST
POST http://localhost:3000/api/postfarm
Content-Type: application/json

{
  "farm_name": "Herbal Smart Greenhouse",
  "crop": "โหระพา",
  "areaSize": "6.80",
  "deviceCount": 9,
  "sensorCount": 6,
  "environment": {
    "sunlight": "Greenhouse",
    "temperature": "27°C",
    "humidity": "74%",
    "waterLevel": "88%"
  },
  "location": {
    "lat": 17.4138,
    "lng": 102.7870
  }
}





# ===========================
# Product 
# ===========================

### GET 
GET http://localhost:3000/api/getproduct

### POST
POST http://localhost:3000/api/postproduct
Content-Type: application/json

{
   "product_name": "test", 
   "quantity":"999", 
   "rai": "99", 
   "image":""
}



