# ===========================
# User
# ===========================

### GET Users All
GET http://localhost:3000/api/users

### GET User/id
GET http://localhost:3000/api/users/15
Content-Type: application/json

{
  "id": "8",
  "username": "newname"
}

### POST Create User {}
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "admin3",
  "email": "admin3@.com",
  "password": "admin123",
  "gender": "male",
  "phone": "0800000001"
}




### PUT Update User/:id {}
PUT http://localhost:3000/api/users/15
Content-Type: application/json

{
  "username": "id8",
  "email": "new@mail.com"
}


### DELETE User/:id
DELETE http://localhost:3000/api/users/14
Content-Type: application/json
### GET Users All
GET http://localhost:3000/api/users


# ===========================
# Authentication 
# ===========================

### Auth Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username":  "top2",
    "password": "1"
}

#### Signup
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
  "username": "",
  "email": "",
  "password": ""
}


### Change password
PUT http://localhost:3000/api/auth/change-password/16
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxNiwiaWF0IjoxNzc3OTczNjI2LCJleHAiOjE3NzgwNjAwMjZ9.Hn4sBul8GCEScLJQomEuFsGJxGdfYYiWDIJ9663V8u4
Content-Type: application/json

{
  "old_password": "123456",
  "new_password": "123456"
}

# ===========================
# Dashboards
# ===========================
### GET 
GET http://localhost:3000/api/getdashboards


### POST
POST http://localhost:3000/api/postdashboards
Content-Type: application/json

{
  "dashboard_name": "testa", 
  "farm_id": "11",
  "temperature": "99",
  "humidity":"99",
  "ph": "99"
}




# ===========================
# Farms
# ===========================
### GET 
GET http://localhost:3000/api/getfarm

### POST
POST http://localhost:3000/api/postfarm
Content-Type: application/json

{
  "farm_name": "ฟาร์มของฉัน",
  "location": { "province": "ขอนแก่น" }, 
  "crop": "ข้าว",
  "areaSize": "10",
  "deviceCount": "10",
  "sensorCount": "5",
  "environment": { "type": "Outdoor" }
}



# ===========================
# Product 
# ===========================

### GET 
GET http://localhost:3000/api/getproduct

### POST
POST http://localhost:3000/api/postproduct
Content-Type: application/json

{
   "product_name": "test", 
   "quantity":"999", 
   "rai": "99", 
   "image":""
}

# ===========================
# Profile
# ===========================

### GET 
GET http://localhost:3000/api/getprofile

### POST
POST http://localhost:3000/api/postprofile
Content-Type: application/json

{
  "firstName": "สมชาย",
  "lastName": "ใจดี",
  "gender": "male", 
  "role": "user",
  "address": "123 หมู่ 4...",
  "phone": "0812345678",
  "email": "somcasdasdsdasdhaiggg@example.com",
  "avatar": "A"
}

